export const alpha2Code = [
    { country: 'af', value: 1 },
    { country: 'al', value: 1 },
    { country: 'dz', value: 1 },
    { country: 'as', value: 1 },
    { country: 'ad', value: 1 },
    { country: 'ao', value: 1 },
    { country: 'ai', value: 1 },
    { country: 'aq', value: 1 },
    { country: 'ag', value: 1 },
    { country: 'ar', value: 1 },
    { country: 'am', value: 1 },
    { country: 'aw', value: 1 },
    { country: 'au', value: 1 },
    { country: 'at', value: 1 },
    { country: 'az', value: 1 },
    { country: 'bs', value: 1 },
    { country: 'bh', value: 1 },
    { country: 'bd', value: 1 },
    { country: 'bb', value: 1 },
    { country: 'by', value: 1 },
    { country: 'be', value: 1 },
    { country: 'bz', value: 1 },
    { country: 'bj', value: 1 },
    { country: 'bm', value: 1 },
    { country: 'bt', value: 1 },
    { country: 'bo', value: 1 },
    { country: 'bq', value: 1 },
    { country: 'ba', value: 1 },
    { country: 'bw', value: 1 },
    { country: 'bv', value: 1 },
    { country: 'br', value: 1 },
    { country: 'io', value: 1 },
    { country: 'bn', value: 1 },
    { country: 'bg', value: 1 },
    { country: 'bf', value: 1 },
    { country: 'bi', value: 1 },
    { country: 'cv', value: 1 },
    { country: 'kh', value: 1 },
    { country: 'cm', value: 1 },
    { country: 'ca', value: 1 },
    { country: 'ky', value: 1 },
    { country: 'cf', value: 1 },
    { country: 'td', value: 1 },
    { country: 'cl', value: 1 },
    { country: 'cn', value: 1 },
    { country: 'cx', value: 1 },
    { country: 'cc', value: 1 },
    { country: 'co', value: 1 },
    { country: 'km', value: 1 },
    { country: 'cd', value: 1 },
    { country: 'cg', value: 1 },
    { country: 'ck', value: 1 },
    { country: 'cr', value: 1 },
    { country: 'hr', value: 1 },
    { country: 'cu', value: 1 },
    { country: 'cw', value: 1 },
    { country: 'cy', value: 1 },
    { country: 'cz', value: 1 },
    { country: 'ci', value: 1 },
    { country: 'dk', value: 1 },
    { country: 'dj', value: 1 },
    { country: 'dm', value: 1 },
    { country: 'do', value: 1 },
    { country: 'ec', value: 1 },
    { country: 'eg', value: 1 },
    { country: 'sv', value: 1 },
    { country: 'gq', value: 1 },
    { country: 'er', value: 1 },
    { country: 'ee', value: 1 },
    { country: 'sz', value: 1 },
    { country: 'et', value: 1 },
    { country: 'fk', value: 1 },
    { country: 'fo', value: 1 },
    { country: 'fj', value: 1 },
    { country: 'fi', value: 1 },
    { country: 'fr', value: 1 },
    { country: 'gf', value: 1 },
    { country: 'pf', value: 1 },
    { country: 'tf', value: 1 },
    { country: 'ga', value: 1 },
    { country: 'gm', value: 1 },
    { country: 'ge', value: 1 },
    { country: 'de', value: 1 },
    { country: 'gh', value: 1 },
    { country: 'gi', value: 1 },
    { country: 'gr', value: 1 },
    { country: 'gl', value: 1 },
    { country: 'gd', value: 1 },
    { country: 'gp', value: 1 },
    { country: 'gu', value: 1 },
    { country: 'gt', value: 1 },
    { country: 'gg', value: 1 },
    { country: 'gn', value: 1 },
    { country: 'gw', value: 1 },
    { country: 'gy', value: 1 },
    { country: 'ht', value: 1 },
    { country: 'hm', value: 1 },
    { country: 'va', value: 1 },
    { country: 'hn', value: 1 },
    { country: 'hk', value: 1 },
    { country: 'hu', value: 1 },
    { country: 'is', value: 1 },
    { country: 'in', value: 1 },
    { country: 'id', value: 1 },
    { country: 'ir', value: 1 },
    { country: 'iq', value: 1 },
    { country: 'ie', value: 1 },
    { country: 'im', value: 1 },
    { country: 'il', value: 1 },
    { country: 'it', value: 1 },
    { country: 'jm', value: 1 },
    { country: 'jp', value: 1 },
    { country: 'je', value: 1 },
    { country: 'jo', value: 1 },
    { country: 'kz', value: 1 },
    { country: 'ke', value: 1 },
    { country: 'ki', value: 1 },
    { country: 'kp', value: 1 },
    { country: 'kr', value: 1 },
    { country: 'kw', value: 1 },
    { country: 'kg', value: 1 },
    { country: 'la', value: 1 },
    { country: 'lv', value: 1 },
    { country: 'lb', value: 1 },
    { country: 'ls', value: 1 },
    { country: 'lr', value: 1 },
    { country: 'ly', value: 1 },
    { country: 'li', value: 1 },
    { country: 'lt', value: 1 },
    { country: 'lu', value: 1 },
    { country: 'mo', value: 1 },
    { country: 'mg', value: 1 },
    { country: 'mw', value: 1 },
    { country: 'my', value: 1 },
    { country: 'mv', value: 1 },
    { country: 'ml', value: 1 },
    { country: 'mt', value: 1 },
    { country: 'mh', value: 1 },
    { country: 'mq', value: 1 },
    { country: 'mr', value: 1 },
    { country: 'mu', value: 1 },
    { country: 'yt', value: 1 },
    { country: 'mx', value: 1 },
    { country: 'fm', value: 1 },
    { country: 'md', value: 1 },
    { country: 'mc', value: 1 },
    { country: 'mn', value: 1 },
    { country: 'me', value: 1 },
    { country: 'ms', value: 1 },
    { country: 'ma', value: 1 },
    { country: 'mz', value: 1 },
    { country: 'mm', value: 1 },
    { country: 'na', value: 1 },
    { country: 'nr', value: 1 },
    { country: 'np', value: 1 },
    { country: 'nl', value: 1 },
    { country: 'nc', value: 1 },
    { country: 'nz', value: 1 },
    { country: 'ni', value: 1 },
    { country: 'ne', value: 1 },
    { country: 'ng', value: 1 },
    { country: 'nu', value: 1 },
    { country: 'nf', value: 1 },
    { country: 'mp', value: 1 },
    { country: 'no', value: 1 },
    { country: 'om', value: 1 },
    { country: 'pk', value: 1 },
    { country: 'pw', value: 1 },
    { country: 'ps', value: 1 },
    { country: 'pa', value: 1 },
    { country: 'pg', value: 1 },
    { country: 'py', value: 1 },
    { country: 'pe', value: 1 },
    { country: 'ph', value: 1 },
    { country: 'pn', value: 1 },
    { country: 'pl', value: 1 },
    { country: 'pt', value: 1 },
    { country: 'pr', value: 1 },
    { country: 'qa', value: 1 },
    { country: 'mk', value: 1 },
    { country: 'ro', value: 1 },
    { country: 'ru', value: 1 },
    { country: 'rw', value: 1 },
    { country: 're', value: 1 },
    { country: 'bl', value: 1 },
    { country: 'sh', value: 1 },
    { country: 'kn', value: 1 },
    { country: 'lc', value: 1 },
    { country: 'mf', value: 1 },
    { country: 'pm', value: 1 },
    { country: 'vc', value: 1 },
    { country: 'ws', value: 1 },
    { country: 'sm', value: 1 },
    { country: 'st', value: 1 },
    { country: 'sa', value: 1 },
    { country: 'sn', value: 1 },
    { country: 'rs', value: 1 },
    { country: 'sc', value: 1 },
    { country: 'sl', value: 1 },
    { country: 'sg', value: 1 },
    { country: 'sx', value: 1 },
    { country: 'sk', value: 1 },
    { country: 'si', value: 1 },
    { country: 'sb', value: 1 },
    { country: 'so', value: 1 },
    { country: 'za', value: 1 },
    { country: 'gs', value: 1 },
    { country: 'ss', value: 1 },
    { country: 'es', value: 1 },
    { country: 'lk', value: 1 },
    { country: 'sd', value: 1 },
    { country: 'sr', value: 1 },
    { country: 'sj', value: 1 },
    { country: 'se', value: 1 },
    { country: 'ch', value: 1 },
    { country: 'sy', value: 1 },
    { country: 'tw', value: 1 },
    { country: 'tj', value: 1 },
    { country: 'tz', value: 1 },
    { country: 'th', value: 1 },
    { country: 'tl', value: 1 },
    { country: 'tg', value: 1 },
    { country: 'tk', value: 1 },
    { country: 'to', value: 1 },
    { country: 'tt', value: 1 },
    { country: 'tn', value: 1 },
    { country: 'tr', value: 1 },
    { country: 'tm', value: 1 },
    { country: 'tc', value: 1 },
    { country: 'tv', value: 1 },
    { country: 'ug', value: 1 },
    { country: 'ua', value: 1 },
    { country: 'ae', value: 1 },
    { country: 'gb', value: 1 },
    { country: 'um', value: 1 },
    { country: 'us', value: 1 },
    { country: 'uy', value: 1 },
    { country: 'uz', value: 1 },
    { country: 'vu', value: 1 },
    { country: 've', value: 1 },
    { country: 'vn', value: 1 },
    { country: 'vg', value: 1 },
    { country: 'vi', value: 1 },
    { country: 'wf', value: 1 },
    { country: 'eh', value: 1 },
    { country: 'ye', value: 1 },
    { country: 'zm', value: 1 },
    { country: 'zw', value: 1 },
    { country: 'ax', value: 1 }
]

export const countryAlpha2Code = [
    ['af', 'AFG', 'Afghanistan'],
    ['al', 'ALB', 'Albania'],
    ['dz', 'DZA', 'Algeria'],
    ['as', 'ASM', 'American Samoa'],
    ['ad', 'AND', 'Andorra'],
    ['ao', 'AGO', 'Angola'],
    ['ai', 'AIA', 'Anguilla'],
    ['aq', 'ATA', 'Antarctica'],
    ['ag', 'ATG', 'Antigua and Barbuda'],
    ['ar', 'ARG', 'Argentina'],
    ['am', 'ARM', 'Armenia'],
    ['aw', 'ABW', 'Aruba'],
    ['au', 'AUS', 'Australia'],
    ['at', 'AUT', 'Austria'],
    ['az', 'AZE', 'Azerbaijan'],
    ['bs', 'BHS', 'Bahamas'],
    ['bh', 'BHR', 'Bahrain'],
    ['bd', 'BGD', 'Bangladesh'],
    ['bb', 'BRB', 'Barbados'],
    ['by', 'BLR', 'Belarus'],
    ['be', 'BEL', 'Belgium'],
    ['bz', 'BLZ', 'Belize'],
    ['bj', 'BEN', 'Benin'],
    ['bm', 'BMU', 'Bermuda'],
    ['bt', 'BTN', 'Bhutan'],
    ['bo', 'BOL', 'Bolivia'],
    ['bq', 'BES', 'Bonaire, Sint Eustatius and Saba'],
    ['ba', 'BIH', 'Bosnia and Herzegovina'],
    ['bw', 'BWA', 'Botswana'],
    ['bv', 'BVT', 'Bouvet Island'],
    ['br', 'BRA', 'Brazil'],
    ['io', 'IOT', 'British Indian Ocean Territory'],
    ['bn', 'BRN', 'Brunei Darussalam'],
    ['bg', 'BGR', 'Bulgaria'],
    ['bf', 'BFA', 'Burkina Faso'],
    ['bi', 'BDI', 'Burundi'],
    ['cv', 'CPV', 'Cabo Verde'],
    ['kh', 'KHM', 'Cambodia'],
    ['cm', 'CMR', 'Cameroon'],
    ['ca', 'CAN', 'Canada'],
    ['ky', 'CYM', 'Cayman Islands'],
    ['cf', 'CAF', 'Central African Republic'],
    ['td', 'TCD', 'Chad'],
    ['cl', 'CHL', 'Chile'],
    ['cn', 'CHN', 'China'],
    ['cx', 'CXR', 'Christmas Island'],
    ['cc', 'CCK', 'Cocos (Keeling) Islands'],
    ['co', 'COL', 'Colombia'],
    ['km', 'COM', 'Comoros'],
    ['cd', 'COD', 'Congo (Democratic Republic)'],
    ['cg', 'COG', 'Congo'],
    ['ck', 'COK', 'Cook Islands'],
    ['cr', 'CRI', 'Costa Rica'],
    ['hr', 'HRV', 'Croatia'],
    ['cu', 'CUB', 'Cuba'],
    ['cw', 'CUW', 'Curaçao'],
    ['cy', 'CYP', 'Cyprus'],
    ['cz', 'CZE', 'Czech Republic'],
    ['ci', 'CIV', "Côte d'Ivoire"],
    ['dk', 'DNK', 'Denmark'],
    ['dj', 'DJI', 'Djibouti'],
    ['dm', 'DMA', 'Dominica'],
    ['do', 'DOM', 'Dominican Republic'],
    ['ec', 'ECU', 'Ecuador'],
    ['eg', 'EGY', 'Egypt'],
    ['sv', 'SLV', 'El Salvador'],
    ['gq', 'GNQ', 'Equatorial Guinea'],
    ['er', 'ERI', 'Eritrea'],
    ['ee', 'EST', 'Estonia'],
    ['sz', 'SWZ', 'Eswatini'],
    ['et', 'ETH', 'Ethiopia'],
    ['fk', 'FLK', 'Falkland Islands'],
    ['fo', 'FRO', 'Faroe Islands'],
    ['fj', 'FJI', 'Fiji'],
    ['fi', 'FIN', 'Finland'],
    ['fr', 'FRA', 'France'],
    ['gf', 'GUF', 'French Guiana'],
    ['pf', 'PYF', 'French Polynesia'],
    ['tf', 'ATF', 'French Southern Territories'],
    ['ga', 'GAB', 'Gabon'],
    ['gm', 'GMB', 'Gambia'],
    ['ge', 'GEO', 'Georgia'],
    ['de', 'DEU', 'Germany'],
    ['gh', 'GHA', 'Ghana'],
    ['gi', 'GIB', 'Gibraltar'],
    ['gr', 'GRC', 'Greece'],
    ['gl', 'GRL', 'Greenland'],
    ['gd', 'GRD', 'Grenada'],
    ['gp', 'GLP', 'Guadeloupe'],
    ['gu', 'GUM', 'Guam'],
    ['gt', 'GTM', 'Guatemala'],
    ['gg', 'GGY', 'Guernsey'],
    ['gn', 'GIN', 'Guinea'],
    ['gw', 'GNB', 'Guinea-Bissau'],
    ['gy', 'GUY', 'Guyana'],
    ['ht', 'HTI', 'Haiti'],
    ['hm', 'HMD', 'Heard Island and McDonald Islands'],
    ['va', 'VAT', 'Holy See'],
    ['hn', 'HND', 'Honduras'],
    ['hk', 'HKG', 'Hong Kong'],
    ['hu', 'HUN', 'Hungary'],
    ['is', 'ISL', 'Iceland'],
    ['in', 'IND', 'India'],
    ['id', 'IDN', 'Indonesia'],
    ['ir', 'IRN', 'Iran'],
    ['iq', 'IRQ', 'Iraq'],
    ['ie', 'IRL', 'Ireland'],
    ['im', 'IMN', 'Isle of Man'],
    ['il', 'ISR', 'Israel'],
    ['it', 'ITA', 'Italy'],
    ['jm', 'JAM', 'Jamaica'],
    ['jp', 'JPN', 'Japan'],
    ['je', 'JEY', 'Jersey'],
    ['jo', 'JOR', 'Jordan'],
    ['kz', 'KAZ', 'Kazakhstan'],
    ['ke', 'KEN', 'Kenya'],
    ['ki', 'KIR', 'Kiribati'],
    ['kp', 'PRK', "Korea (Democratic People's Republic)"],
    ['kr', 'KOR', 'Korea (Republic)'],
    ['kw', 'KWT', 'Kuwait'],
    ['kg', 'KGZ', 'Kyrgyzstan'],
    ['la', 'LAO', "Lao People's Democratic Republic"],
    ['lv', 'LVA', 'Latvia'],
    ['lb', 'LBN', 'Lebanon'],
    ['ls', 'LSO', 'Lesotho'],
    ['lr', 'LBR', 'Liberia'],
    ['ly', 'LBY', 'Libya'],
    ['li', 'LIE', 'Liechtenstein'],
    ['lt', 'LTU', 'Lithuania'],
    ['lu', 'LUX', 'Luxembourg'],
    ['mo', 'MAC', 'Macao'],
    ['mg', 'MDG', 'Madagascar'],
    ['mw', 'MWI', 'Malawi'],
    ['my', 'MYS', 'Malaysia'],
    ['mv', 'MDV', 'Maldives'],
    ['ml', 'MLI', 'Mali'],
    ['mt', 'MLT', 'Malta'],
    ['mh', 'MHL', 'Marshall Islands'],
    ['mq', 'MTQ', 'Martinique'],
    ['mr', 'MRT', 'Mauritania'],
    ['mu', 'MUS', 'Mauritius'],
    ['yt', 'MYT', 'Mayotte'],
    ['mx', 'MEX', 'Mexico'],
    ['fm', 'FSM', 'Micronesia (Federated States)'],
    ['md', 'MDA', 'Moldova'],
    ['mc', 'MCO', 'Monaco'],
    ['mn', 'MNG', 'Mongolia'],
    ['me', 'MNE', 'Montenegro'],
    ['ms', 'MSR', 'Montserrat'],
    ['ma', 'MAR', 'Morocco'],
    ['mz', 'MOZ', 'Mozambique'],
    ['mm', 'MMR', 'Myanmar'],
    ['na', 'NAM', 'Namibia'],
    ['nr', 'NRU', 'Nauru'],
    ['np', 'NPL', 'Nepal'],
    ['nl', 'NLD', 'Netherlands'],
    ['nc', 'NCL', 'New Caledonia'],
    ['nz', 'NZL', 'New Zealand'],
    ['ni', 'NIC', 'Nicaragua'],
    ['ne', 'NER', 'Niger'],
    ['ng', 'NGA', 'Nigeria'],
    ['nu', 'NIU', 'Niue'],
    ['nf', 'NFK', 'Norfolk Island'],
    ['mp', 'MNP', 'Northern Mariana Islands'],
    ['no', 'NOR', 'Norway'],
    ['om', 'OMN', 'Oman'],
    ['pk', 'PAK', 'Pakistan'],
    ['pw', 'PLW', 'Palau'],
    ['ps', 'PSE', 'Palestine, State of'],
    ['pa', 'PAN', 'Panama'],
    ['pg', 'PNG', 'Papua New Guinea'],
    ['py', 'PRY', 'Paraguay'],
    ['pe', 'PER', 'Peru'],
    ['ph', 'PHL', 'Philippines'],
    ['pn', 'PCN', 'Pitcairn'],
    ['pl', 'POL', 'Poland'],
    ['pt', 'PRT', 'Portugal'],
    ['pr', 'PRI', 'Puerto Rico'],
    ['qa', 'QAT', 'Qatar'],
    ['mk', 'MKD', 'Republic of North Macedonia'],
    ['ro', 'ROU', 'Romania'],
    ['ru', 'RUS', 'Russia'],
    ['rw', 'RWA', 'Rwanda'],
    ['re', 'REU', 'Réunion'],
    ['bl', 'BLM', 'Saint Barthélemy'],
    ['sh', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha'],
    ['kn', 'KNA', 'Saint Kitts and Nevis'],
    ['lc', 'LCA', 'Saint Lucia'],
    ['mf', 'MAF', 'Saint Martin (French part)'],
    ['pm', 'SPM', 'Saint Pierre and Miquelon'],
    ['vc', 'VCT', 'Saint Vincent and the Grenadines'],
    ['ws', 'WSM', 'Samoa'],
    ['sm', 'SMR', 'San Marino'],
    ['st', 'STP', 'Sao Tome and Principe'],
    ['sa', 'SAU', 'Saudi Arabia'],
    ['sn', 'SEN', 'Senegal'],
    ['rs', 'SRB', 'Serbia'],
    ['sc', 'SYC', 'Seychelles'],
    ['sl', 'SLE', 'Sierra Leone'],
    ['sg', 'SGP', 'Singapore'],
    ['sx', 'SXM', 'Sint Maarten (Dutch part)'],
    ['sk', 'SVK', 'Slovakia'],
    ['si', 'SVN', 'Slovenia'],
    ['sb', 'SLB', 'Solomon Islands'],
    ['so', 'SOM', 'Somalia'],
    ['za', 'ZAF', 'South Africa'],
    ['gs', 'SGS', 'South Georgia and the South Sandwich Islands'],
    ['ss', 'SSD', 'South Sudan'],
    ['es', 'ESP', 'Spain'],
    ['lk', 'LKA', 'Sri Lanka'],
    ['sd', 'SDN', 'Sudan'],
    ['sr', 'SUR', 'Suriname'],
    ['sj', 'SJM', 'Svalbard and Jan Mayen'],
    ['se', 'SWE', 'Sweden'],
    ['ch', 'CHE', 'Switzerland'],
    ['sy', 'SYR', 'Syrian Arab Republic'],
    ['tw', 'TWN', 'Taiwan'],
    ['tj', 'TJK', 'Tajikistan'],
    ['tz', 'TZA', 'Tanzania'],
    ['th', 'THA', 'Thailand'],
    ['tl', 'TLS', 'Timor-Leste'],
    ['tg', 'TGO', 'Togo'],
    ['tk', 'TKL', 'Tokelau'],
    ['to', 'TON', 'Tonga'],
    ['tt', 'TTO', 'Trinidad and Tobago'],
    ['tn', 'TUN', 'Tunisia'],
    ['tr', 'TUR', 'Turkey'],
    ['tm', 'TKM', 'Turkmenistan'],
    ['tc', 'TCA', 'Turks and Caicos Islands'],
    ['tv', 'TUV', 'Tuvalu'],
    ['ug', 'UGA', 'Uganda'],
    ['ua', 'UKR', 'Ukraine'],
    ['ae', 'ARE', 'United Arab Emirates'],
    ['gb', 'GBR', 'United Kingdom'],
    ['um', 'UMI', 'United States Minor Outlying Islands'],
    ['us', 'USA', 'United States of America'],
    ['uy', 'URY', 'Uruguay'],
    ['uz', 'UZB', 'Uzbekistan'],
    ['vu', 'VUT', 'Vanuatu'],
    ['ve', 'VEN', 'Venezuela'],
    ['vn', 'VNM', 'Viet Nam'],
    ['vg', 'VGB', 'Virgin Islands (British)'],
    ['vi', 'VIR', 'Virgin Islands (U.S.)'],
    ['wf', 'WLF', 'Wallis and Futuna'],
    ['eh', 'ESH', 'Western Sahara'],
    ['ye', 'YEM', 'Yemen'],
    ['zm', 'ZMB', 'Zambia'],
    ['zw', 'ZWE', 'Zimbabwe'],
    ['ax', 'ALA', 'Åland Islands']
]
