export const alpha2Code = [
    { country: 'af', value: 1 },
    { country: 'al', value: 2 },
    { country: 'dz', value: 3 },
    { country: 'as', value: 4 },
    { country: 'ad', value: 5 },
    { country: 'ao', value: 6 },
    { country: 'ai', value: 7 },
    { country: 'aq', value: 8 },
    { country: 'ag', value: 9 },
    { country: 'ar', value: 10 },
    { country: 'am', value: 11 },
    { country: 'aw', value: 12 },
    { country: 'au', value: 13 },
    { country: 'at', value: 14 },
    { country: 'az', value: 15 },
    { country: 'bs', value: 16 },
    { country: 'bh', value: 17 },
    { country: 'bd', value: 18 },
    { country: 'bb', value: 19 },
    { country: 'by', value: 20 },
    { country: 'be', value: 21 },
    { country: 'bz', value: 22 },
    { country: 'bj', value: 23 },
    { country: 'bm', value: 24 },
    { country: 'bt', value: 25 },
    { country: 'bo', value: 26 },
    { country: 'bq', value: 27 },
    { country: 'ba', value: 28 },
    { country: 'bw', value: 29 },
    { country: 'bv', value: 30 },
    { country: 'br', value: 31 },
    { country: 'io', value: 32 },
    { country: 'bn', value: 33 },
    { country: 'bg', value: 34 },
    { country: 'bf', value: 35 },
    { country: 'bi', value: 36 },
    { country: 'cv', value: 37 },
    { country: 'kh', value: 38 },
    { country: 'cm', value: 39 },
    { country: 'ca', value: 40 },
    { country: 'ky', value: 41 },
    { country: 'cf', value: 42 },
    { country: 'td', value: 43 },
    { country: 'cl', value: 44 },
    { country: 'cn', value: 45 },
    { country: 'cx', value: 46 },
    { country: 'cc', value: 47 },
    { country: 'co', value: 48 },
    { country: 'km', value: 49 },
    { country: 'cd', value: 50 },
    { country: 'cg', value: 51 },
    { country: 'ck', value: 52 },
    { country: 'cr', value: 53 },
    { country: 'hr', value: 54 },
    { country: 'cu', value: 55 },
    { country: 'cw', value: 56 },
    { country: 'cy', value: 57 },
    { country: 'cz', value: 58 },
    { country: 'ci', value: 59 },
    { country: 'dk', value: 60 },
    { country: 'dj', value: 61 },
    { country: 'dm', value: 62 },
    { country: 'do', value: 63 },
    { country: 'ec', value: 64 },
    { country: 'eg', value: 65 },
    { country: 'sv', value: 66 },
    { country: 'gq', value: 67 },
    { country: 'er', value: 68 },
    { country: 'ee', value: 69 },
    { country: 'sz', value: 70 },
    { country: 'et', value: 71 },
    { country: 'fk', value: 72 },
    { country: 'fo', value: 73 },
    { country: 'fj', value: 74 },
    { country: 'fi', value: 75 },
    { country: 'fr', value: 76 },
    { country: 'gf', value: 77 },
    { country: 'pf', value: 78 },
    { country: 'tf', value: 79 },
    { country: 'ga', value: 80 },
    { country: 'gm', value: 81 },
    { country: 'ge', value: 82 },
    { country: 'de', value: 83 },
    { country: 'gh', value: 84 },
    { country: 'gi', value: 85 },
    { country: 'gr', value: 86 },
    { country: 'gl', value: 87 },
    { country: 'gd', value: 88 },
    { country: 'gp', value: 89 },
    { country: 'gu', value: 90 },
    { country: 'gt', value: 91 },
    { country: 'gg', value: 92 },
    { country: 'gn', value: 93 },
    { country: 'gw', value: 94 },
    { country: 'gy', value: 95 },
    { country: 'ht', value: 96 },
    { country: 'hm', value: 97 },
    { country: 'va', value: 98 },
    { country: 'hn', value: 99 },
    { country: 'hk', value: 100 },
    { country: 'hu', value: 101 },
    { country: 'is', value: 102 },
    { country: 'in', value: 103 },
    { country: 'id', value: 104 },
    { country: 'ir', value: 105 },
    { country: 'iq', value: 106 },
    { country: 'ie', value: 107 },
    { country: 'im', value: 108 },
    { country: 'il', value: 109 },
    { country: 'it', value: 110 },
    { country: 'jm', value: 111 },
    { country: 'jp', value: 112 },
    { country: 'je', value: 113 },
    { country: 'jo', value: 114 },
    { country: 'kz', value: 115 },
    { country: 'ke', value: 116 },
    { country: 'ki', value: 117 },
    { country: 'kp', value: 118 },
    { country: 'kr', value: 119 },
    { country: 'kw', value: 120 },
    { country: 'kg', value: 121 },
    { country: 'la', value: 122 },
    { country: 'lv', value: 123 },
    { country: 'lb', value: 124 },
    { country: 'ls', value: 125 },
    { country: 'lr', value: 126 },
    { country: 'ly', value: 127 },
    { country: 'li', value: 128 },
    { country: 'lt', value: 129 },
    { country: 'lu', value: 130 },
    { country: 'mo', value: 131 },
    { country: 'mg', value: 132 },
    { country: 'mw', value: 133 },
    { country: 'my', value: 134 },
    { country: 'mv', value: 135 },
    { country: 'ml', value: 136 },
    { country: 'mt', value: 137 },
    { country: 'mh', value: 138 },
    { country: 'mq', value: 139 },
    { country: 'mr', value: 140 },
    { country: 'mu', value: 141 },
    { country: 'yt', value: 142 },
    { country: 'mx', value: 143 },
    { country: 'fm', value: 144 },
    { country: 'md', value: 145 },
    { country: 'mc', value: 146 },
    { country: 'mn', value: 147 },
    { country: 'me', value: 148 },
    { country: 'ms', value: 149 },
    { country: 'ma', value: 150 },
    { country: 'mz', value: 151 },
    { country: 'mm', value: 152 },
    { country: 'na', value: 153 },
    { country: 'nr', value: 154 },
    { country: 'np', value: 155 },
    { country: 'nl', value: 156 },
    { country: 'nc', value: 157 },
    { country: 'nz', value: 158 },
    { country: 'ni', value: 159 },
    { country: 'ne', value: 160 },
    { country: 'ng', value: 161 },
    { country: 'nu', value: 162 },
    { country: 'nf', value: 163 },
    { country: 'mp', value: 164 },
    { country: 'no', value: 165 },
    { country: 'om', value: 166 },
    { country: 'pk', value: 167 },
    { country: 'pw', value: 168 },
    { country: 'ps', value: 169 },
    { country: 'pa', value: 170 },
    { country: 'pg', value: 171 },
    { country: 'py', value: 172 },
    { country: 'pe', value: 173 },
    { country: 'ph', value: 174 },
    { country: 'pn', value: 175 },
    { country: 'pl', value: 176 },
    { country: 'pt', value: 177 },
    { country: 'pr', value: 178 },
    { country: 'qa', value: 179 },
    { country: 'mk', value: 180 },
    { country: 'ro', value: 181 },
    { country: 'ru', value: 182 },
    { country: 'rw', value: 183 },
    { country: 're', value: 184 },
    { country: 'bl', value: 185 },
    { country: 'sh', value: 186 },
    { country: 'kn', value: 187 },
    { country: 'lc', value: 188 },
    { country: 'mf', value: 189 },
    { country: 'pm', value: 190 },
    { country: 'vc', value: 191 },
    { country: 'ws', value: 192 },
    { country: 'sm', value: 193 },
    { country: 'st', value: 194 },
    { country: 'sa', value: 195 },
    { country: 'sn', value: 196 },
    { country: 'rs', value: 197 },
    { country: 'sc', value: 198 },
    { country: 'sl', value: 199 },
    { country: 'sg', value: 200 },
    { country: 'sx', value: 201 },
    { country: 'sk', value: 202 },
    { country: 'si', value: 203 },
    { country: 'sb', value: 204 },
    { country: 'so', value: 205 },
    { country: 'za', value: 206 },
    { country: 'gs', value: 207 },
    { country: 'ss', value: 208 },
    { country: 'es', value: 209 },
    { country: 'lk', value: 210 },
    { country: 'sd', value: 211 },
    { country: 'sr', value: 212 },
    { country: 'sj', value: 213 },
    { country: 'se', value: 214 },
    { country: 'ch', value: 215 },
    { country: 'sy', value: 216 },
    { country: 'tw', value: 217 },
    { country: 'tj', value: 218 },
    { country: 'tz', value: 219 },
    { country: 'th', value: 220 },
    { country: 'tl', value: 221 },
    { country: 'tg', value: 222 },
    { country: 'tk', value: 223 },
    { country: 'to', value: 224 },
    { country: 'tt', value: 225 },
    { country: 'tn', value: 226 },
    { country: 'tr', value: 227 },
    { country: 'tm', value: 228 },
    { country: 'tc', value: 229 },
    { country: 'tv', value: 230 },
    { country: 'ug', value: 231 },
    { country: 'ua', value: 232 },
    { country: 'ae', value: 233 },
    { country: 'gb', value: 234 },
    { country: 'um', value: 235 },
    { country: 'us', value: 236 },
    { country: 'uy', value: 237 },
    { country: 'uz', value: 238 },
    { country: 'vu', value: 239 },
    { country: 've', value: 240 },
    { country: 'vn', value: 241 },
    { country: 'vg', value: 242 },
    { country: 'vi', value: 243 },
    { country: 'wf', value: 244 },
    { country: 'eh', value: 245 },
    { country: 'ye', value: 246 },
    { country: 'zm', value: 247 },
    { country: 'zw', value: 248 },
    { country: 'ax', value: 24 }
]

export const countryCode = [
    ['af', 'AFG'],
    ['al', 'ALB'],
    ['dz', 'DZA'],
    ['as', 'ASM'],
    ['ad', 'AND'],
    ['ao', 'AGO'],
    ['ai', 'AIA'],
    ['aq', 'ATA'],
    ['ag', 'ATG'],
    ['ar', 'ARG'],
    ['am', 'ARM'],
    ['aw', 'ABW'],
    ['au', 'AUS'],
    ['at', 'AUT'],
    ['az', 'AZE'],
    ['bs', 'BHS'],
    ['bh', 'BHR'],
    ['bd', 'BGD'],
    ['bb', 'BRB'],
    ['by', 'BLR'],
    ['be', 'BEL'],
    ['bz', 'BLZ'],
    ['bj', 'BEN'],
    ['bm', 'BMU'],
    ['bt', 'BTN'],
    ['bo', 'BOL'],
    ['bq', 'BES'],
    ['ba', 'BIH'],
    ['bw', 'BWA'],
    ['bv', 'BVT'],
    ['br', 'BRA'],
    ['io', 'IOT'],
    ['bn', 'BRN'],
    ['bg', 'BGR'],
    ['bf', 'BFA'],
    ['bi', 'BDI'],
    ['cv', 'CPV'],
    ['kh', 'KHM'],
    ['cm', 'CMR'],
    ['ca', 'CAN'],
    ['ky', 'CYM'],
    ['cf', 'CAF'],
    ['td', 'TCD'],
    ['cl', 'CHL'],
    ['cn', 'CHN'],
    ['cx', 'CXR'],
    ['cc', 'CCK'],
    ['co', 'COL'],
    ['km', 'COM'],
    ['cd', 'COD'],
    ['cg', 'COG'],
    ['ck', 'COK'],
    ['cr', 'CRI'],
    ['hr', 'HRV'],
    ['cu', 'CUB'],
    ['cw', 'CUW'],
    ['cy', 'CYP'],
    ['cz', 'CZE'],
    ['ci', 'CIV'],
    ['dk', 'DNK'],
    ['dj', 'DJI'],
    ['dm', 'DMA'],
    ['do', 'DOM'],
    ['ec', 'ECU'],
    ['eg', 'EGY'],
    ['sv', 'SLV'],
    ['gq', 'GNQ'],
    ['er', 'ERI'],
    ['ee', 'EST'],
    ['sz', 'SWZ'],
    ['et', 'ETH'],
    ['fk', 'FLK'],
    ['fo', 'FRO'],
    ['fj', 'FJI'],
    ['fi', 'FIN'],
    ['fr', 'FRA'],
    ['gf', 'GUF'],
    ['pf', 'PYF'],
    ['tf', 'ATF'],
    ['ga', 'GAB'],
    ['gm', 'GMB'],
    ['ge', 'GEO'],
    ['de', 'DEU'],
    ['gh', 'GHA'],
    ['gi', 'GIB'],
    ['gr', 'GRC'],
    ['gl', 'GRL'],
    ['gd', 'GRD'],
    ['gp', 'GLP'],
    ['gu', 'GUM'],
    ['gt', 'GTM'],
    ['gg', 'GGY'],
    ['gn', 'GIN'],
    ['gw', 'GNB'],
    ['gy', 'GUY'],
    ['ht', 'HTI'],
    ['hm', 'HMD'],
    ['va', 'VAT'],
    ['hn', 'HND'],
    ['hk', 'HKG'],
    ['hu', 'HUN'],
    ['is', 'ISL'],
    ['in', 'IND'],
    ['id', 'IDN'],
    ['ir', 'IRN'],
    ['iq', 'IRQ'],
    ['ie', 'IRL'],
    ['im', 'IMN'],
    ['il', 'ISR'],
    ['it', 'ITA'],
    ['jm', 'JAM'],
    ['jp', 'JPN'],
    ['je', 'JEY'],
    ['jo', 'JOR'],
    ['kz', 'KAZ'],
    ['ke', 'KEN'],
    ['ki', 'KIR'],
    ['kp', 'PRK'],
    ['kr', 'KOR'],
    ['kw', 'KWT'],
    ['kg', 'KGZ'],
    ['la', 'LAO'],
    ['lv', 'LVA'],
    ['lb', 'LBN'],
    ['ls', 'LSO'],
    ['lr', 'LBR'],
    ['ly', 'LBY'],
    ['li', 'LIE'],
    ['lt', 'LTU'],
    ['lu', 'LUX'],
    ['mo', 'MAC'],
    ['mg', 'MDG'],
    ['mw', 'MWI'],
    ['my', 'MYS'],
    ['mv', 'MDV'],
    ['ml', 'MLI'],
    ['mt', 'MLT'],
    ['mh', 'MHL'],
    ['mq', 'MTQ'],
    ['mr', 'MRT'],
    ['mu', 'MUS'],
    ['yt', 'MYT'],
    ['mx', 'MEX'],
    ['fm', 'FSM'],
    ['md', 'MDA'],
    ['mc', 'MCO'],
    ['mn', 'MNG'],
    ['me', 'MNE'],
    ['ms', 'MSR'],
    ['ma', 'MAR'],
    ['mz', 'MOZ'],
    ['mm', 'MMR'],
    ['na', 'NAM'],
    ['nr', 'NRU'],
    ['np', 'NPL'],
    ['nl', 'NLD'],
    ['nc', 'NCL'],
    ['nz', 'NZL'],
    ['ni', 'NIC'],
    ['ne', 'NER'],
    ['ng', 'NGA'],
    ['nu', 'NIU'],
    ['nf', 'NFK'],
    ['mp', 'MNP'],
    ['no', 'NOR'],
    ['om', 'OMN'],
    ['pk', 'PAK'],
    ['pw', 'PLW'],
    ['ps', 'PSE'],
    ['pa', 'PAN'],
    ['pg', 'PNG'],
    ['py', 'PRY'],
    ['pe', 'PER'],
    ['ph', 'PHL'],
    ['pn', 'PCN'],
    ['pl', 'POL'],
    ['pt', 'PRT'],
    ['pr', 'PRI'],
    ['qa', 'QAT'],
    ['mk', 'MKD'],
    ['ro', 'ROU'],
    ['ru', 'RUS'],
    ['rw', 'RWA'],
    ['re', 'REU'],
    ['bl', 'BLM'],
    ['sh', 'SHN'],
    ['kn', 'KNA'],
    ['lc', 'LCA'],
    ['mf', 'MAF'],
    ['pm', 'SPM'],
    ['vc', 'VCT'],
    ['ws', 'WSM'],
    ['sm', 'SMR'],
    ['st', 'STP'],
    ['sa', 'SAU'],
    ['sn', 'SEN'],
    ['rs', 'SRB'],
    ['sc', 'SYC'],
    ['sl', 'SLE'],
    ['sg', 'SGP'],
    ['sx', 'SXM'],
    ['sk', 'SVK'],
    ['si', 'SVN'],
    ['sb', 'SLB'],
    ['so', 'SOM'],
    ['za', 'ZAF'],
    ['gs', 'SGS'],
    ['ss', 'SSD'],
    ['es', 'ESP'],
    ['lk', 'LKA'],
    ['sd', 'SDN'],
    ['sr', 'SUR'],
    ['sj', 'SJM'],
    ['se', 'SWE'],
    ['ch', 'CHE'],
    ['sy', 'SYR'],
    ['tw', 'TWN'],
    ['tj', 'TJK'],
    ['tz', 'TZA'],
    ['th', 'THA'],
    ['tl', 'TLS'],
    ['tg', 'TGO'],
    ['tk', 'TKL'],
    ['to', 'TON'],
    ['tt', 'TTO'],
    ['tn', 'TUN'],
    ['tr', 'TUR'],
    ['tm', 'TKM'],
    ['tc', 'TCA'],
    ['tv', 'TUV'],
    ['ug', 'UGA'],
    ['ua', 'UKR'],
    ['ae', 'ARE'],
    ['gb', 'GBR'],
    ['um', 'UMI'],
    ['us', 'USA'],
    ['uy', 'URY'],
    ['uz', 'UZB'],
    ['vu', 'VUT'],
    ['ve', 'VEN'],
    ['vn', 'VNM'],
    ['vg', 'VGB'],
    ['vi', 'VIR'],
    ['wf', 'WLF'],
    ['eh', 'ESH'],
    ['ye', 'YEM'],
    ['zm', 'ZMB'],
    ['zw', 'ZWE'],
    ['ax', 'ALA']
]

export const alpha3Code = [
    'AFG',
    'ALB',
    'DZA',
    'ASM',
    'AND',
    'AGO',
    'AIA',
    'ATA',
    'ATG',
    'ARG',
    'ARM',
    'ABW',
    'AUS',
    'AUT',
    'AZE',
    'BHS',
    'BHR',
    'BGD',
    'BRB',
    'BLR',
    'BEL',
    'BLZ',
    'BEN',
    'BMU',
    'BTN',
    'BOL',
    'BES',
    'BIH',
    'BWA',
    'BVT',
    'BRA',
    'IOT',
    'BRN',
    'BGR',
    'BFA',
    'BDI',
    'CPV',
    'KHM',
    'CMR',
    'CAN',
    'CYM',
    'CAF',
    'TCD',
    'CHL',
    'CHN',
    'CXR',
    'CCK',
    'COL',
    'COM',
    'COD',
    'COG',
    'COK',
    'CRI',
    'HRV',
    'CUB',
    'CUW',
    'CYP',
    'CZE',
    'CIV',
    'DNK',
    'DJI',
    'DMA',
    'DOM',
    'ECU',
    'EGY',
    'SLV',
    'GNQ',
    'ERI',
    'EST',
    'SWZ',
    'ETH',
    'FLK',
    'FRO',
    'FJI',
    'FIN',
    'FRA',
    'GUF',
    'PYF',
    'ATF',
    'GAB',
    'GMB',
    'GEO',
    'DEU',
    'GHA',
    'GIB',
    'GRC',
    'GRL',
    'GRD',
    'GLP',
    'GUM',
    'GTM',
    'GGY',
    'GIN',
    'GNB',
    'GUY',
    'HTI',
    'HMD',
    'VAT',
    'HND',
    'HKG',
    'HUN',
    'ISL',
    'IND',
    'IDN',
    'IRN',
    'IRQ',
    'IRL',
    'IMN',
    'ISR',
    'ITA',
    'JAM',
    'JPN',
    'JEY',
    'JOR',
    'KAZ',
    'KEN',
    'KIR',
    'PRK',
    'KOR',
    'KWT',
    'KGZ',
    'LAO',
    'LVA',
    'LBN',
    'LSO',
    'LBR',
    'LBY',
    'LIE',
    'LTU',
    'LUX',
    'MAC',
    'MDG',
    'MWI',
    'MYS',
    'MDV',
    'MLI',
    'MLT',
    'MHL',
    'MTQ',
    'MRT',
    'MUS',
    'MYT',
    'MEX',
    'FSM',
    'MDA',
    'MCO',
    'MNG',
    'MNE',
    'MSR',
    'MAR',
    'MOZ',
    'MMR',
    'NAM',
    'NRU',
    'NPL',
    'NLD',
    'NCL',
    'NZL',
    'NIC',
    'NER',
    'NGA',
    'NIU',
    'NFK',
    'MNP',
    'NOR',
    'OMN',
    'PAK',
    'PLW',
    'PSE',
    'PAN',
    'PNG',
    'PRY',
    'PER',
    'PHL',
    'PCN',
    'POL',
    'PRT',
    'PRI',
    'QAT',
    'MKD',
    'ROU',
    'RUS',
    'RWA',
    'REU',
    'BLM',
    'SHN',
    'KNA',
    'LCA',
    'MAF',
    'SPM',
    'VCT',
    'WSM',
    'SMR',
    'STP',
    'SAU',
    'SEN',
    'SRB',
    'SYC',
    'SLE',
    'SGP',
    'SXM',
    'SVK',
    'SVN',
    'SLB',
    'SOM',
    'ZAF',
    'SGS',
    'SSD',
    'ESP',
    'LKA',
    'SDN',
    'SUR',
    'SJM',
    'SWE',
    'CHE',
    'SYR',
    'TWN',
    'TJK',
    'TZA',
    'THA',
    'TLS',
    'TGO',
    'TKL',
    'TON',
    'TTO',
    'TUN',
    'TUR',
    'TKM',
    'TCA',
    'TUV',
    'UGA',
    'UKR',
    'ARE',
    'GBR',
    'UMI',
    'USA',
    'URY',
    'UZB',
    'VUT',
    'VEN',
    'VNM',
    'VGB',
    'VIR',
    'WLF',
    'ESH',
    'YEM',
    'ZMB',
    'ZWE',
    'ALA'
]

export const countryNames = [
    ['Afghanistan', 1],
    ['Albania', 2],
    ['Algeria', 3],
    ['American Samoa', 4],
    ['Andorra', 5],
    ['Angola', 6],
    ['Anguilla', 7],
    ['Antarctica', 8],
    ['Antigua and Barbuda', 9],
    ['Argentina', 10],
    ['Armenia', 11],
    ['Aruba', 12],
    ['Australia', 13],
    ['Austria', 14],
    ['Azerbaijan', 15],
    ['Bahamas', 16],
    ['Bahrain', 17],
    ['Bangladesh', 18],
    ['Barbados', 19],
    ['Belarus', 20],
    ['Belgium', 21],
    ['Belize', 22],
    ['Benin', 23],
    ['Bermuda', 24],
    ['Bhutan', 25],
    ['Bolivia', 26],
    ['Bonaire, Sint Eustatius and Saba', 27],
    ['Bosnia and Herzegovina', 28],
    ['Botswana', 29],
    ['Bouvet Island', 30],
    ['Brazil', 31],
    ['British Indian Ocean Territory', 32],
    ['Brunei Darussalam', 33],
    ['Bulgaria', 34],
    ['Burkina Faso', 35],
    ['Burundi', 36],
    ['Cabo Verde', 37],
    ['Cambodia', 38],
    ['Cameroon', 39],
    ['Canada', 40],
    ['Cayman Islands', 41],
    ['Central African Republic', 42],
    ['Chad', 43],
    ['Chile', 44],
    ['China', 45],
    ['Christmas Island', 46],
    ['Cocos (Keeling) Islands', 47],
    ['Colombia', 48],
    ['Comoros', 49],
    ['Congo, the Democratic Republic of the', 50],
    ['Congo', 51],
    ['Cook Islands', 52],
    ['Costa Rica', 53],
    ['Croatia', 54],
    ['Cuba', 55],
    ['Curaçao', 56],
    ['Cyprus', 57],
    ['Czechia', 58],
    ["Côte d'Ivoire", 59],
    ['Denmark', 60],
    ['Djibouti', 61],
    ['Dominica', 62],
    ['Dominican Republic', 63],
    ['Ecuador', 64],
    ['Egypt', 65],
    ['El Salvador', 66],
    ['Equatorial Guinea', 67],
    ['Eritrea', 68],
    ['Estonia', 69],
    ['Eswatini', 70],
    ['Ethiopia', 71],
    ['Falkland Islands (Malvinas)', 72],
    ['Faroe Islands', 73],
    ['Fiji', 74],
    ['Finland', 75],
    ['France', 76],
    ['French Guiana', 77],
    ['French Polynesia', 78],
    ['French Southern Territories', 79],
    ['Gabon', 80],
    ['Gambia', 81],
    ['Georgia', 82],
    ['Germany', 83],
    ['Ghana', 84],
    ['Gibraltar', 85],
    ['Greece', 86],
    ['Greenland', 87],
    ['Grenada', 88],
    ['Guadeloupe', 89],
    ['Guam', 90],
    ['Guatemala', 91],
    ['Guernsey', 92],
    ['Guinea', 93],
    ['Guinea-Bissau', 94],
    ['Guyana', 95],
    ['Haiti', 96],
    ['Heard Island and McDonald Islands', 97],
    ['Holy See', 98],
    ['Honduras', 99],
    ['Hong Kong', 100],
    ['Hungary', 101],
    ['Iceland', 102],
    ['India', 103],
    ['Indonesia', 104],
    ['Iran, Islamic Republic of', 105],
    ['Iraq', 106],
    ['Ireland', 107],
    ['Isle of Man', 108],
    ['Israel', 109],
    ['Italy', 110],
    ['Jamaica', 111],
    ['Japan', 112],
    ['Jersey', 113],
    ['Jordan', 114],
    ['Kazakhstan', 115],
    ['Kenya', 116],
    ['Kiribati', 117],
    ["Korea, Democratic People's Republic of", 118],
    ['Korea, Republic of', 119],
    ['Kuwait', 120],
    ['Kyrgyzstan', 121],
    ["Lao People's Democratic Republic", 122],
    ['Latvia', 123],
    ['Lebanon', 124],
    ['Lesotho', 125],
    ['Liberia', 126],
    ['Libya', 127],
    ['Liechtenstein', 128],
    ['Lithuania', 129],
    ['Luxembourg', 130],
    ['Macao', 131],
    ['Madagascar', 132],
    ['Malawi', 133],
    ['Malaysia', 134],
    ['Maldives', 135],
    ['Mali', 136],
    ['Malta', 137],
    ['Marshall Islands', 138],
    ['Martinique', 139],
    ['Mauritania', 140],
    ['Mauritius', 141],
    ['Mayotte', 142],
    ['Mexico', 143],
    ['Micronesia, Federated States of', 144],
    ['Moldova, Republic of', 145],
    ['Monaco', 146],
    ['Mongolia', 147],
    ['Montenegro', 148],
    ['Montserrat', 149],
    ['Morocco', 150],
    ['Mozambique', 151],
    ['Myanmar', 152],
    ['Namibia', 153],
    ['Nauru', 154],
    ['Nepal', 155],
    ['Netherlands', 156],
    ['New Caledonia', 157],
    ['New Zealand', 158],
    ['Nicaragua', 159],
    ['Niger', 160],
    ['Nigeria', 161],
    ['Niue', 162],
    ['Norfolk Island', 163],
    ['Northern Mariana Islands', 164],
    ['Norway', 165],
    ['Oman', 166],
    ['Pakistan', 167],
    ['Palau', 168],
    ['Palestine, State of', 169],
    ['Panama', 170],
    ['Papua New Guinea', 171],
    ['Paraguay', 172],
    ['Peru', 173],
    ['Philippines', 174],
    ['Pitcairn', 175],
    ['Poland', 176],
    ['Portugal', 177],
    ['Puerto Rico', 178],
    ['Qatar', 179],
    ['Republic of North Macedonia', 180],
    ['Romania', 181],
    ['Russian Federation', 182],
    ['Rwanda', 183],
    ['Réunion', 184],
    ['Saint Barthélemy', 185],
    ['Saint Helena, Ascension and Tristan da Cunha', 186],
    ['Saint Kitts and Nevis', 187],
    ['Saint Lucia', 188],
    ['Saint Martin (French part)', 189],
    ['Saint Pierre and Miquelon', 190],
    ['Saint Vincent and the Grenadines', 191],
    ['Samoa', 192],
    ['San Marino', 193],
    ['Sao Tome and Principe', 194],
    ['Saudi Arabia', 195],
    ['Senegal', 196],
    ['Serbia', 197],
    ['Seychelles', 198],
    ['Sierra Leone', 199],
    ['Singapore', 200],
    ['Sint Maarten (Dutch part)', 201],
    ['Slovakia', 202],
    ['Slovenia', 203],
    ['Solomon Islands', 204],
    ['Somalia', 205],
    ['South Africa', 206],
    ['South Georgia and the South Sandwich Islands', 207],
    ['South Sudan', 208],
    ['Spain', 209],
    ['Sri Lanka', 210],
    ['Sudan', 211],
    ['Suriname', 212],
    ['Svalbard and Jan Mayen', 213],
    ['Sweden', 214],
    ['Switzerland', 215],
    ['Syrian Arab Republic', 216],
    ['Taiwan, Province of China', 217],
    ['Tajikistan', 218],
    ['Tanzania, United Republic of', 219],
    ['Thailand', 220],
    ['Timor-Leste', 221],
    ['Togo', 222],
    ['Tokelau', 223],
    ['Tonga', 224],
    ['Trinidad and Tobago', 225],
    ['Tunisia', 226],
    ['Turkey', 227],
    ['Turkmenistan', 228],
    ['Turks and Caicos Islands', 229],
    ['Tuvalu', 230],
    ['Uganda', 231],
    ['Ukraine', 232],
    ['United Arab Emirates', 233],
    ['United Kingdom of Great Britain and Northern Ireland', 234],
    ['United States Minor Outlying Islands', 235],
    ['United States of America', 236],
    ['Uruguay', 237],
    ['Uzbekistan', 238],
    ['Vanuatu', 239],
    ['Venezuela (Bolivarian Republic of)', 240],
    ['Viet Nam', 241],
    ['Virgin Islands (British)', 242],
    ['Virgin Islands (U.S.)', 243],
    ['Wallis and Futuna', 244],
    ['Western Sahara', 245],
    ['Yemen', 246],
    ['Zambia', 247],
    ['Zimbabwe', 248],
    ['Åland Islands', 249]
]
