export const alpha2Code = [
    { country: 'af', value: 1 },
    { country: 'al', value: 1 },
    { country: 'dz', value: 1 },
    { country: 'as', value: 1 },
    { country: 'ad', value: 1 },
    { country: 'ao', value: 1 },
    { country: 'ai', value: 1 },
    { country: 'aq', value: 1 },
    { country: 'ag', value: 1 },
    { country: 'ar', value: 1 },
    { country: 'am', value: 1 },
    { country: 'aw', value: 1 },
    { country: 'au', value: 1 },
    { country: 'at', value: 1 },
    { country: 'az', value: 1 },
    { country: 'bs', value: 1 },
    { country: 'bh', value: 1 },
    { country: 'bd', value: 1 },
    { country: 'bb', value: 1 },
    { country: 'by', value: 1 },
    { country: 'be', value: 1 },
    { country: 'bz', value: 1 },
    { country: 'bj', value: 1 },
    { country: 'bm', value: 1 },
    { country: 'bt', value: 1 },
    { country: 'bo', value: 1 },
    { country: 'bq', value: 1 },
    { country: 'ba', value: 1 },
    { country: 'bw', value: 1 },
    { country: 'bv', value: 1 },
    { country: 'br', value: 1 },
    { country: 'io', value: 1 },
    { country: 'bn', value: 1 },
    { country: 'bg', value: 1 },
    { country: 'bf', value: 1 },
    { country: 'bi', value: 1 },
    { country: 'cv', value: 1 },
    { country: 'kh', value: 1 },
    { country: 'cm', value: 1 },
    { country: 'ca', value: 1 },
    { country: 'ky', value: 1 },
    { country: 'cf', value: 1 },
    { country: 'td', value: 1 },
    { country: 'cl', value: 1 },
    { country: 'cn', value: 1 },
    { country: 'cx', value: 1 },
    { country: 'cc', value: 1 },
    { country: 'co', value: 1 },
    { country: 'km', value: 1 },
    { country: 'cd', value: 1 },
    { country: 'cg', value: 1 },
    { country: 'ck', value: 1 },
    { country: 'cr', value: 1 },
    { country: 'hr', value: 1 },
    { country: 'cu', value: 1 },
    { country: 'cw', value: 1 },
    { country: 'cy', value: 1 },
    { country: 'cz', value: 1 },
    { country: 'ci', value: 1 },
    { country: 'dk', value: 1 },
    { country: 'dj', value: 1 },
    { country: 'dm', value: 1 },
    { country: 'do', value: 1 },
    { country: 'ec', value: 1 },
    { country: 'eg', value: 1 },
    { country: 'sv', value: 1 },
    { country: 'gq', value: 1 },
    { country: 'er', value: 1 },
    { country: 'ee', value: 1 },
    { country: 'sz', value: 1 },
    { country: 'et', value: 1 },
    { country: 'fk', value: 1 },
    { country: 'fo', value: 1 },
    { country: 'fj', value: 1 },
    { country: 'fi', value: 1 },
    { country: 'fr', value: 1 },
    { country: 'gf', value: 1 },
    { country: 'pf', value: 1 },
    { country: 'tf', value: 1 },
    { country: 'ga', value: 1 },
    { country: 'gm', value: 1 },
    { country: 'ge', value: 1 },
    { country: 'de', value: 1 },
    { country: 'gh', value: 1 },
    { country: 'gi', value: 1 },
    { country: 'gr', value: 1 },
    { country: 'gl', value: 1 },
    { country: 'gd', value: 1 },
    { country: 'gp', value: 1 },
    { country: 'gu', value: 1 },
    { country: 'gt', value: 1 },
    { country: 'gg', value: 1 },
    { country: 'gn', value: 1 },
    { country: 'gw', value: 1 },
    { country: 'gy', value: 1 },
    { country: 'ht', value: 1 },
    { country: 'hm', value: 1 },
    { country: 'va', value: 1 },
    { country: 'hn', value: 1 },
    { country: 'hk', value: 1 },
    { country: 'hu', value: 1 },
    { country: 'is', value: 1 },
    { country: 'in', value: 1 },
    { country: 'id', value: 1 },
    { country: 'ir', value: 1 },
    { country: 'iq', value: 1 },
    { country: 'ie', value: 1 },
    { country: 'im', value: 1 },
    { country: 'il', value: 1 },
    { country: 'it', value: 1 },
    { country: 'jm', value: 1 },
    { country: 'jp', value: 1 },
    { country: 'je', value: 1 },
    { country: 'jo', value: 1 },
    { country: 'kz', value: 1 },
    { country: 'ke', value: 1 },
    { country: 'ki', value: 1 },
    { country: 'kp', value: 1 },
    { country: 'kr', value: 1 },
    { country: 'kw', value: 1 },
    { country: 'kg', value: 1 },
    { country: 'la', value: 1 },
    { country: 'lv', value: 1 },
    { country: 'lb', value: 1 },
    { country: 'ls', value: 1 },
    { country: 'lr', value: 1 },
    { country: 'ly', value: 1 },
    { country: 'li', value: 1 },
    { country: 'lt', value: 1 },
    { country: 'lu', value: 1 },
    { country: 'mo', value: 1 },
    { country: 'mg', value: 1 },
    { country: 'mw', value: 1 },
    { country: 'my', value: 1 },
    { country: 'mv', value: 1 },
    { country: 'ml', value: 1 },
    { country: 'mt', value: 1 },
    { country: 'mh', value: 1 },
    { country: 'mq', value: 1 },
    { country: 'mr', value: 1 },
    { country: 'mu', value: 1 },
    { country: 'yt', value: 1 },
    { country: 'mx', value: 1 },
    { country: 'fm', value: 1 },
    { country: 'md', value: 1 },
    { country: 'mc', value: 1 },
    { country: 'mn', value: 1 },
    { country: 'me', value: 1 },
    { country: 'ms', value: 1 },
    { country: 'ma', value: 1 },
    { country: 'mz', value: 1 },
    { country: 'mm', value: 1 },
    { country: 'na', value: 1 },
    { country: 'nr', value: 1 },
    { country: 'np', value: 1 },
    { country: 'nl', value: 1 },
    { country: 'nc', value: 1 },
    { country: 'nz', value: 1 },
    { country: 'ni', value: 1 },
    { country: 'ne', value: 1 },
    { country: 'ng', value: 1 },
    { country: 'nu', value: 1 },
    { country: 'nf', value: 1 },
    { country: 'mp', value: 1 },
    { country: 'no', value: 1 },
    { country: 'om', value: 1 },
    { country: 'pk', value: 1 },
    { country: 'pw', value: 1 },
    { country: 'ps', value: 1 },
    { country: 'pa', value: 1 },
    { country: 'pg', value: 1 },
    { country: 'py', value: 1 },
    { country: 'pe', value: 1 },
    { country: 'ph', value: 1 },
    { country: 'pn', value: 1 },
    { country: 'pl', value: 1 },
    { country: 'pt', value: 1 },
    { country: 'pr', value: 1 },
    { country: 'qa', value: 1 },
    { country: 'mk', value: 1 },
    { country: 'ro', value: 1 },
    { country: 'ru', value: 1 },
    { country: 'rw', value: 1 },
    { country: 're', value: 1 },
    { country: 'bl', value: 1 },
    { country: 'sh', value: 1 },
    { country: 'kn', value: 1 },
    { country: 'lc', value: 1 },
    { country: 'mf', value: 1 },
    { country: 'pm', value: 1 },
    { country: 'vc', value: 1 },
    { country: 'ws', value: 1 },
    { country: 'sm', value: 1 },
    { country: 'st', value: 1 },
    { country: 'sa', value: 1 },
    { country: 'sn', value: 1 },
    { country: 'rs', value: 1 },
    { country: 'sc', value: 1 },
    { country: 'sl', value: 1 },
    { country: 'sg', value: 1 },
    { country: 'sx', value: 1 },
    { country: 'sk', value: 1 },
    { country: 'si', value: 1 },
    { country: 'sb', value: 1 },
    { country: 'so', value: 1 },
    { country: 'za', value: 1 },
    { country: 'gs', value: 1 },
    { country: 'ss', value: 1 },
    { country: 'es', value: 1 },
    { country: 'lk', value: 1 },
    { country: 'sd', value: 1 },
    { country: 'sr', value: 1 },
    { country: 'sj', value: 1 },
    { country: 'se', value: 1 },
    { country: 'ch', value: 1 },
    { country: 'sy', value: 1 },
    { country: 'tw', value: 1 },
    { country: 'tj', value: 1 },
    { country: 'tz', value: 1 },
    { country: 'th', value: 1 },
    { country: 'tl', value: 1 },
    { country: 'tg', value: 1 },
    { country: 'tk', value: 1 },
    { country: 'to', value: 1 },
    { country: 'tt', value: 1 },
    { country: 'tn', value: 1 },
    { country: 'tr', value: 1 },
    { country: 'tm', value: 1 },
    { country: 'tc', value: 1 },
    { country: 'tv', value: 1 },
    { country: 'ug', value: 1 },
    { country: 'ua', value: 1 },
    { country: 'ae', value: 1 },
    { country: 'gb', value: 1 },
    { country: 'um', value: 1 },
    { country: 'us', value: 1 },
    { country: 'uy', value: 1 },
    { country: 'uz', value: 1 },
    { country: 'vu', value: 1 },
    { country: 've', value: 1 },
    { country: 'vn', value: 1 },
    { country: 'vg', value: 1 },
    { country: 'vi', value: 1 },
    { country: 'wf', value: 1 },
    { country: 'eh', value: 1 },
    { country: 'ye', value: 1 },
    { country: 'zm', value: 1 },
    { country: 'zw', value: 1 },
    { country: 'ax', value: 1 }
]

export const countryAlpha2Code = [
    ['af', 'AFG', 'TR'],
    ['al', 'ALB', 'TR'],
    ['dz', 'DZA', 'TR'],
    ['as', 'ASM', 'TR'],
    ['ad', 'AND', 'TR'],
    ['ao', 'AGO', 'TR'],
    ['ai', 'AIA', 'TR'],
    ['aq', 'ATA', 'TR'],
    ['ag', 'ATG', 'TR'],
    ['ar', 'ARG', 'TR'],
    ['am', 'ARM', 'TR'],
    ['aw', 'ABW', 'TR'],
    ['au', 'AUS', 'TR'],
    ['at', 'AUT', 'TR'],
    ['az', 'AZE', 'TR'],
    ['bs', 'BHS', 'TR'],
    ['bh', 'BHR', 'TR'],
    ['bd', 'BGD', 'TR'],
    ['bb', 'BRB', 'TR'],
    ['by', 'BLR', 'TR'],
    ['be', 'BEL', 'TR'],
    ['bz', 'BLZ', 'TR'],
    ['bj', 'BEN', 'TR'],
    ['bm', 'BMU', 'TR'],
    ['bt', 'BTN', 'TR'],
    ['bo', 'BOL', 'TR'],
    ['bq', 'BES', 'TR'],
    ['ba', 'BIH', 'TR'],
    ['bw', 'BWA', 'TR'],
    ['bv', 'BVT', 'TR'],
    ['br', 'BRA', 'TR'],
    ['io', 'IOT', 'TR'],
    ['bn', 'BRN', 'TR'],
    ['bg', 'BGR', 'TR'],
    ['bf', 'BFA', 'TR'],
    ['bi', 'BDI', 'TR'],
    ['cv', 'CPV', 'TR'],
    ['kh', 'KHM', 'TR'],
    ['cm', 'CMR', 'TR'],
    ['ca', 'CAN', 'TR'],
    ['ky', 'CYM', 'TR'],
    ['cf', 'CAF', 'TR'],
    ['td', 'TCD', 'TR'],
    ['cl', 'CHL', 'TR'],
    ['cn', 'CHN', 'TR'],
    ['cx', 'CXR', 'TR'],
    ['cc', 'CCK', 'TR'],
    ['co', 'COL', 'TR'],
    ['km', 'COM', 'TR'],
    ['cd', 'COD', 'TR'],
    ['cg', 'COG', 'TR'],
    ['ck', 'COK', 'TR'],
    ['cr', 'CRI', 'TR'],
    ['hr', 'HRV', 'TR'],
    ['cu', 'CUB', 'TR'],
    ['cw', 'CUW', 'TR'],
    ['cy', 'CYP', 'TR'],
    ['cz', 'CZE', 'TR'],
    ['ci', 'CIV', 'TR'],
    ['dk', 'DNK', 'TR'],
    ['dj', 'DJI', 'TR'],
    ['dm', 'DMA', 'TR'],
    ['do', 'DOM', 'TR'],
    ['ec', 'ECU', 'TR'],
    ['eg', 'EGY', 'TR'],
    ['sv', 'SLV', 'TR'],
    ['gq', 'GNQ', 'TR'],
    ['er', 'ERI', 'TR'],
    ['ee', 'EST', 'TR'],
    ['sz', 'SWZ', 'TR'],
    ['et', 'ETH', 'TR'],
    ['fk', 'FLK', 'TR'],
    ['fo', 'FRO', 'TR'],
    ['fj', 'FJI', 'TR'],
    ['fi', 'FIN', 'TR'],
    ['fr', 'FRA', 'TR'],
    ['gf', 'GUF', 'TR'],
    ['pf', 'PYF', 'TR'],
    ['tf', 'ATF', 'TR'],
    ['ga', 'GAB', 'TR'],
    ['gm', 'GMB', 'TR'],
    ['ge', 'GEO', 'TR'],
    ['de', 'DEU', 'TR'],
    ['gh', 'GHA', 'TR'],
    ['gi', 'GIB', 'TR'],
    ['gr', 'GRC', 'TR'],
    ['gl', 'GRL', 'TR'],
    ['gd', 'GRD', 'TR'],
    ['gp', 'GLP', 'TR'],
    ['gu', 'GUM', 'TR'],
    ['gt', 'GTM', 'TR'],
    ['gg', 'GGY', 'TR'],
    ['gn', 'GIN', 'TR'],
    ['gw', 'GNB', 'TR'],
    ['gy', 'GUY', 'TR'],
    ['ht', 'HTI', 'TR'],
    ['hm', 'HMD', 'TR'],
    ['va', 'VAT', 'TR'],
    ['hn', 'HND', 'TR'],
    ['hk', 'HKG', 'TR'],
    ['hu', 'HUN', 'TR'],
    ['is', 'ISL', 'TR'],
    ['in', 'IND', 'TR'],
    ['id', 'IDN', 'TR'],
    ['ir', 'IRN', 'TR'],
    ['iq', 'IRQ', 'TR'],
    ['ie', 'IRL', 'TR'],
    ['im', 'IMN', 'TR'],
    ['il', 'ISR', 'TR'],
    ['it', 'ITA', 'TR'],
    ['jm', 'JAM', 'TR'],
    ['jp', 'JPN', 'TR'],
    ['je', 'JEY', 'TR'],
    ['jo', 'JOR', 'TR'],
    ['kz', 'KAZ', 'TR'],
    ['ke', 'KEN', 'TR'],
    ['ki', 'KIR', 'TR'],
    ['kp', 'PRK', 'TR'],
    ['kr', 'KOR', 'TR'],
    ['kw', 'KWT', 'TR'],
    ['kg', 'KGZ', 'TR'],
    ['la', 'LAO', 'TR'],
    ['lv', 'LVA', 'TR'],
    ['lb', 'LBN', 'TR'],
    ['ls', 'LSO', 'TR'],
    ['lr', 'LBR', 'TR'],
    ['ly', 'LBY', 'TR'],
    ['li', 'LIE', 'TR'],
    ['lt', 'LTU', 'TR'],
    ['lu', 'LUX', 'TR'],
    ['mo', 'MAC', 'TR'],
    ['mg', 'MDG', 'TR'],
    ['mw', 'MWI', 'TR'],
    ['my', 'MYS', 'TR'],
    ['mv', 'MDV', 'TR'],
    ['ml', 'MLI', 'TR'],
    ['mt', 'MLT', 'TR'],
    ['mh', 'MHL', 'TR'],
    ['mq', 'MTQ', 'TR'],
    ['mr', 'MRT', 'TR'],
    ['mu', 'MUS', 'TR'],
    ['yt', 'MYT', 'TR'],
    ['mx', 'MEX', 'TR'],
    ['fm', 'FSM', 'TR'],
    ['md', 'MDA', 'TR'],
    ['mc', 'MCO', 'TR'],
    ['mn', 'MNG', 'TR'],
    ['me', 'MNE', 'TR'],
    ['ms', 'MSR', 'TR'],
    ['ma', 'MAR', 'TR'],
    ['mz', 'MOZ', 'TR'],
    ['mm', 'MMR', 'TR'],
    ['na', 'NAM', 'TR'],
    ['nr', 'NRU', 'TR'],
    ['np', 'NPL', 'TR'],
    ['nl', 'NLD', 'TR'],
    ['nc', 'NCL', 'TR'],
    ['nz', 'NZL', 'TR'],
    ['ni', 'NIC', 'TR'],
    ['ne', 'NER', 'TR'],
    ['ng', 'NGA', 'TR'],
    ['nu', 'NIU', 'TR'],
    ['nf', 'NFK', 'TR'],
    ['mp', 'MNP', 'TR'],
    ['no', 'NOR', 'TR'],
    ['om', 'OMN', 'TR'],
    ['pk', 'PAK', 'TR'],
    ['pw', 'PLW', 'TR'],
    ['ps', 'PSE', 'TR'],
    ['pa', 'PAN', 'TR'],
    ['pg', 'PNG', 'TR'],
    ['py', 'PRY', 'TR'],
    ['pe', 'PER', 'TR'],
    ['ph', 'PHL', 'TR'],
    ['pn', 'PCN', 'TR'],
    ['pl', 'POL', 'TR'],
    ['pt', 'PRT', 'TR'],
    ['pr', 'PRI', 'TR'],
    ['qa', 'QAT', 'TR'],
    ['mk', 'MKD', 'TR'],
    ['ro', 'ROU', 'TR'],
    ['ru', 'RUS', 'TR'],
    ['rw', 'RWA', 'TR'],
    ['re', 'REU', 'TR'],
    ['bl', 'BLM', 'TR'],
    ['sh', 'SHN', 'TR'],
    ['kn', 'KNA', 'TR'],
    ['lc', 'LCA', 'TR'],
    ['mf', 'MAF', 'TR'],
    ['pm', 'SPM', 'TR'],
    ['vc', 'VCT', 'TR'],
    ['ws', 'WSM', 'TR'],
    ['sm', 'SMR', 'TR'],
    ['st', 'STP', 'TR'],
    ['sa', 'SAU', 'TR'],
    ['sn', 'SEN', 'TR'],
    ['rs', 'SRB', 'TR'],
    ['sc', 'SYC', 'TR'],
    ['sl', 'SLE', 'TR'],
    ['sg', 'SGP', 'TR'],
    ['sx', 'SXM', 'TR'],
    ['sk', 'SVK', 'TR'],
    ['si', 'SVN', 'TR'],
    ['sb', 'SLB', 'TR'],
    ['so', 'SOM', 'TR'],
    ['za', 'ZAF', 'TR'],
    ['gs', 'SGS', 'TR'],
    ['ss', 'SSD', 'TR'],
    ['es', 'ESP', 'TR'],
    ['lk', 'LKA', 'TR'],
    ['sd', 'SDN', 'TR'],
    ['sr', 'SUR', 'TR'],
    ['sj', 'SJM', 'TR'],
    ['se', 'SWE', 'TR'],
    ['ch', 'CHE', 'TR'],
    ['sy', 'SYR', 'TR'],
    ['tw', 'TWN', 'TR'],
    ['tj', 'TJK', 'TR'],
    ['tz', 'TZA', 'TR'],
    ['th', 'THA', 'TR'],
    ['tl', 'TLS', 'TR'],
    ['tg', 'TGO', 'TR'],
    ['tk', 'TKL', 'TR'],
    ['to', 'TON', 'TR'],
    ['tt', 'TTO', 'TR'],
    ['tn', 'TUN', 'TR'],
    ['tr', 'TUR', 'TR'],
    ['tm', 'TKM', 'TR'],
    ['tc', 'TCA', 'TR'],
    ['tv', 'TUV', 'TR'],
    ['ug', 'UGA', 'TR'],
    ['ua', 'UKR', 'TR'],
    ['ae', 'ARE', 'TR'],
    ['gb', 'GBR', 'TR'],
    ['um', 'UMI', 'TR'],
    ['us', 'USA', 'TR'],
    ['uy', 'URY', 'TR'],
    ['uz', 'UZB', 'TR'],
    ['vu', 'VUT', 'TR'],
    ['ve', 'VEN', 'TR'],
    ['vn', 'VNM', 'TR'],
    ['vg', 'VGB', 'TR'],
    ['vi', 'VIR', 'TR'],
    ['wf', 'WLF', 'TR'],
    ['eh', 'ESH', 'TR'],
    ['ye', 'YEM', 'TR'],
    ['zm', 'ZMB', 'TR'],
    ['zw', 'ZWE', 'TR'],
    ['ax', 'ALA', 'TR']
]
